"""Test fixtures: a fake repository index spanning several subsystems.

Fully implemented support module — you do NOT edit this file. The exercise lives
in exploration.py; this module just provides a realistic index to explore.

REPO_INDEX models the output of a "search-first" scan: each entry is a file path
plus a one-line summary of what that file does. A real Grep/Glob pass would
produce something like this — paths and short descriptions, not full contents.
"""

# 10 entries across distinct subsystems (auth, billing, search, ratelimit, ui,
# notifications). Enough that select_files MUST return a proper subset.
REPO_INDEX = [
    {"path": "auth/login.py",
     "summary": "user login flow and session creation"},
    {"path": "auth/tokens.py",
     "summary": "JWT token issue refresh and session validation"},
    {"path": "auth/password.py",
     "summary": "password hashing and reset"},
    {"path": "billing/invoice.py",
     "summary": "invoice generation and line item totals"},
    {"path": "billing/payment.py",
     "summary": "payment processing and refunds"},
    {"path": "search/indexer.py",
     "summary": "full text search indexing pipeline"},
    {"path": "search/query.py",
     "summary": "search query parsing and ranking"},
    {"path": "ratelimit/limiter.py",
     "summary": "request rate limiting middleware"},
    {"path": "ui/dashboard.py",
     "summary": "dashboard rendering and widgets"},
    {"path": "notifications/email.py",
     "summary": "transactional email sending"},
]


def make_long_text(n_lines, prefix="line"):
    """Build a deterministic multi-line string with n_lines lines.

    Used by the tests to simulate verbose tool output (e.g. a long file read or
    a recursive directory listing) that must be trimmed before entering context.
    """
    return "\n".join("{} {}".format(prefix, i) for i in range(n_lines))
