"""Test fixtures for chapter 7.5 — human review workflows and confidence calibration.

These are fully implemented support data; you do not edit this file. The exercise
is in review.py. Tests import these fixtures to exercise your functions.
"""

# A labeled calibration set: predictions that have been checked against ground truth.
# Each row is {"confidence": float in [0, 1], "correct": bool}. The high-confidence
# decile here is deliberately over-confident (predicted ~0.93 but only ~0.67 correct)
# so a calibration report surfaces a visible gap.
LABELED = [
    {"confidence": 0.95, "correct": True},
    {"confidence": 0.92, "correct": False},
    {"confidence": 0.91, "correct": True},
    {"confidence": 0.45, "correct": False},
    {"confidence": 0.41, "correct": True},
]

# An extracted record: field name -> {"value", "confidence"}. Two fields are below a
# typical 0.80 review threshold (tax_id, due_date); two are above (vendor, total).
RECORD = {
    "vendor":   {"value": "Acme Corp",  "confidence": 0.99},
    "total":    {"value": "1240.00",    "confidence": 0.97},
    "tax_id":   {"value": "12-3456789", "confidence": 0.41},
    "due_date": {"value": "2026-06-15", "confidence": 0.62},
}

# A population of records carrying a categorical stratum field, for QA sampling.
# Imbalanced on purpose: "invoice" is common, "contract" is rare — uniform random
# sampling would routinely miss "contract".
RECORDS = (
    [{"id": i, "category": "invoice"} for i in range(60)]
    + [{"id": 100 + i, "category": "receipt"} for i in range(30)]
    + [{"id": 200 + i, "category": "contract"} for i in range(10)]
)
