"""Test fixtures for the context-manager exercise.

Fully implemented — you do NOT edit this file. It provides:

- ``sample_conversation()``: a long, realistic support conversation as a list
  of message dicts, each shaped ``{"role", "content", "tokens"}``. The first
  message has role ``"system"`` and is the pinned standing instruction.
- ``fake_summarizer(msgs)``: a DETERMINISTIC stand-in for a real Claude
  summarization call. It takes the list of messages being collapsed and returns
  a single summary string. Deterministic so tests are reproducible.
"""

from typing import Dict, List


def fake_summarizer(msgs: List[Dict]) -> str:
    """A deterministic fake summarizer.

    In production this would be a Claude call that reads ``msgs`` and writes a
    concise digest. Here it returns a fixed-shape string so tests can assert on
    it exactly, with no network and no nondeterminism.
    """
    return "SUMMARY: " + str(len(msgs)) + " earlier turns"


def sample_conversation() -> List[Dict]:
    """A long support conversation.

    Index 0 is the pinned system message. The remaining messages alternate
    user/assistant turns. ``tokens`` is the per-message size used for budgeting.
    Total tokens here is well over a small budget, so this fixture exercises the
    over-budget summarization path; slice it or lower the per-message tokens to
    exercise the under-budget path.
    """
    return [
        {"role": "system", "content": "You are a billing support agent. Account ID is ACC-4417.", "tokens": 40},
        {"role": "user", "content": "My invoice for March looks wrong.", "tokens": 30},
        {"role": "assistant", "content": "Let me pull up invoice INV-309 for account ACC-4417.", "tokens": 30},
        {"role": "user", "content": "It shows two charges of $50.", "tokens": 30},
        {"role": "assistant", "content": "I see a duplicate charge on line 2. Investigating.", "tokens": 30},
        {"role": "user", "content": "Was I double-billed?", "tokens": 30},
        {"role": "assistant", "content": "Yes — the second $50 is a duplicate. I will refund it.", "tokens": 30},
        {"role": "user", "content": "How long does the refund take?", "tokens": 30},
        {"role": "assistant", "content": "Refunds post in 3-5 business days to the original card.", "tokens": 30},
        {"role": "user", "content": "Can you also email me a receipt?", "tokens": 30},
        {"role": "assistant", "content": "Done — receipt for INV-309 sent to your address on file.", "tokens": 30},
        {"role": "user", "content": "Great, anything I need to do on my end?", "tokens": 30},
        {"role": "assistant", "content": "Nothing further; the refund is automatic. Reference: REF-882.", "tokens": 30},
    ]
